name: Release Pipeline

on:
  push:
    tags:
      # Se declanșează DOAR când trimiți un tag valid conform Semantic Versioning (ex: v1.0.0, v1.0.2-rc.2)
      # Orice push obișnuit pe un branch va fi ignorat direct de GitHub Actions.
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
      - 'v[0-9]+\.[0-9]+\.[0-9]+-*'

permissions:
  contents: read

jobs:
  pre-flight:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Version
        id: version
        shell: bash
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG#v}"

          echo "Version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run linter
        run: npm run lint

  package:
    needs: pre-flight
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        id: repo
        shell: bash
        run: |
          IMAGE=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        run: |
          docker build \
            -t ghcr.io/${{ steps.repo.outputs.image }}:${{ needs.pre-flight.outputs.version }} .

      - name: Docker Push
        run: |
          docker push ghcr.io/${{ steps.repo.outputs.image }}:${{ needs.pre-flight.outputs.version }}

  release:
    needs:
      - pre-flight
      - package

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy --dir=dist --prod
